import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner";
import { CartProvider } from "@/context/cart-context";
import ConditionalFooter from "@/components/conditional-footer";
import { AuthProvider } from "@/context/auth-context";
import WhatsappButton from "@/components/whatsapp-button";
import ChatButton from "@/components/ChatButton";
import { MessagesProvider } from "@/context/messages-context";

const anton = localFont({
  src: "../../public/fonts/anton.woff2",
  weight: "400",
  variable: "--font-anton",
  display: "swap",
});

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={anton.variable}>
      <body className="antialiased">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
        >
          <AuthProvider>
            <CartProvider>
              <MessagesProvider>
                <Toaster position="top-right" richColors /> {/* Configuración de Sonner */}
                {children}
                <WhatsappButton />
                <ChatButton />
                <ConditionalFooter />
              </MessagesProvider>
            </CartProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
