import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner";
import { CartProvider } from "@/context/cart-context";
import ConditionalFooter from "@/components/conditional-footer";
import { AuthProvider } from "@/context/auth-context";
import WhatsappButton from "@/components/whatsapp-button";
import ChatButton from "@/components/ChatButton";

export const dynamic = "force-dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
        >
          <AuthProvider>
            <CartProvider>
                <Toaster position="top-right" richColors /> {/* Configuración de Sonner */}
                {children}
                <WhatsappButton />
                <ChatButton />
                <ConditionalFooter />
            </CartProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
